[package]
name = "schismatic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
staticvec = "0.11.5"
parking_lot = "0.12.0"

[dependencies.clap]
version = "3.1"
features = ["derive", "cargo", "env", "unicode", "wrap_help"]
